  
name: Dev Publish
on: 
  push:
    branches:
      - main



jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      
      - name: Update Dependecies
        run: npm update

      - name: Install Depedencies
        run: npm install

      - name: Javascript Teste
        run: npm run test



  Npm-Publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Npm and Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          id_run=$(echo ${{ github.run_id }} |cut -b 1-5)
          old="$(cat package.json |grep "version"|head -1)"
          sed "s|$old|\"version\": \"23.$id_run.0beta\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Update Packages
        run: npm update

      - name: Install Packages
        run: npm install

      - name: Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}