name: The Docker Image Check
on: 
  pull_request:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: checkout
        uses: actions/checkout@master

      - name: Build Nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          tags: bdsmaneger:test_${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
