name: Publish dev npm package
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/*/**'
      - 'package-lock.json'
      - '.devcontainer/**'
      - 'CHANGELOG.md'
      - 'Docker/*/**'

jobs:
  Npm_Dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: Edit Version
        run: |
          id_run1=$(echo ${{ github.run_id }} |cut -b 1-2)
          id_run2=$(echo ${{ github.run_id }} |cut -b 3-6)
          id_run3=$(echo ${{ github.run_id }} |cut -b 7-)
          old="$(cat package.json |grep "version"|head -1)"
          new_version="$id_run1.$id_run2.$id_run3"
          sed "s|$old|\"version\": \"$new_version\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}