name: The nightly Docker Image

on: [push]
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - uses: actions/checkout@master
      - name: Build Nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Docker/Dockerfile
          tags: |
            sirherobrine23/bdsmaneger:nightly
            bdsmaneger/maneger:nightly
          platforms: linux/amd64,linux/arm64