  
name: Publish Dev in npm
on: [push]
jobs:
  npm-check-vunarability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: |
          if npm update|grep -q 'found 0 vulnerabilities';then
          exit 0
          else
          echo 'Vunarability found, leaving with error'
          exit 1
          fi
      - run: |
          if npm install|grep -q 'found 0 vulnerabilities';then
          exit 0
          else
          echo 'Vunarability found, leaving with error'
          exit 1
          fi
      - name: Jest Test
        run: npm run test
  Npm-Publish:
    needs: npm-check-vunarability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Npm and Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          id_run=$(echo ${{ github.run_id }} |cut -b 1-5)
          old="$(cat package.json |grep 'version'|head -1)"
          sed "s|$old|\"version\": \"23.$id_run.0beta\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Update Packages
        run: npm update

      - name: Install Packages
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}