name: "The Docker Image Check or Dependabot Automerge"
on: 
  push:
    branches:
      - dependabot*
      - main
  pull_request:
    branches:
      - dependabot*
      - main

env:
  DOCKER_ARCHS: linux/amd64,linux/arm64

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge Dependecies
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"

  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build Nightly
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          file: Dockerfile
          push: false
          target: bdscore
          tags: bdsmaneger:test_${{ github.run_id }}
          platforms: ${{ env.DOCKER_ARCHS }}
