name: Stable Publish
on:
  push: 
    tags:
      - "*.*"
      - "v*.*"
    branches:
      - stable
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Update Dependecies
        run: |
          npm update &> /tmp/update.txt
          if cat /tmp/update.txt |grep -q "found 0 vulnerabilities";then
          cat /tmp/update.txt
          exit 0
          else
          cat /tmp/update.txt
          echo "Vunarability found, leaving with error"
          exit 1
          fi
      - name: Install Depedencies
        run: |
          npm install &> /tmp/install.txt
          if cat /tmp/install.txt |grep -q "found 0 vulnerabilities";then
          cat /tmp/install.txt
          exit 0
          else
          cat /tmp/install.txt
          echo "Vunarability found, leaving with error"
          exit 1
          fi

      - name: Check Latest
        run: |
          sudo apt install jq -y
          latest="$(npm show bds_maneger_api version)"
          package_version="$(cat package.json| jq .version)"
          if [ $package_version == $latest ];then
          echo "This version has already been published"
          exit 1
          fi

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}