name: Docker Image and Npm Packages - Publish
on:
  push: 
    tags:
      - v**
      - V**

env:
  DOCKER_ARCHS: linux/amd64,linux/arm64

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Docker:
    runs-on: ubuntu-latest
    name: Docker Core Image
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          file: Dockerfile
          target: bdscore
          tags: |
            bdsmaneger/maneger:latest
            bdsmaneger/maneger:${{ github.run_id }}
          platforms: ${{ env.DOCKER_ARCHS }}