name: Docker Image and Npm Packages - Publish
on:
  push: 
    tags:
      - v**
      - V**
jobs:
  Publish:
    runs-on: ubuntu-latest
    container: dsmaneger/node_image:latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Docker:
    runs-on: ubuntu-latest
    name: Docker Core Image
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Docker/Dockerfile
          tags: |
            sirherobrine23/bdsmaneger:latest
            sirherobrine23/bdsmaneger:${{ github.run_id }}
            bdsmaneger/maneger:latest
            bdsmaneger/maneger:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
