name: Npm Packages Stable
on:
  push: 
    tags:
      - v**
      - V**

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}