name: Stable Publish
on:
  push: 
    branches:
      - stable
    paths-ignore:
      - 'README.md'
      - '.github/*/**'
      - 'package-lock.json'
      - '.devcontainer/**'
      - 'CHANGELOG.md'
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Install Depedencies
        run: |
          npm install &> /tmp/install.txt
          if cat /tmp/install.txt |grep -q "found 0 vulnerabilities";then
          cat /tmp/install.txt
          exit 0
          else
          cat /tmp/install.txt
          echo "Vunarability found, leaving with error"
          exit 1
          fi

      - name: Check Latest
        run: |
          sudo apt install jq -y
          latest="$(npm show bds_maneger_api version)"
          package_version="$(cat package.json| jq .version)"
          if [ $package_version == $latest ];then
          echo "This version has already been published"
          exit 1
          fi

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Infos
        run: bash .github/workflows/get_version.sh

      - name: Tag
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Bds Maneger API v${{ env.bds_api_version }}
          tag_name: ${{ env.bds_api_version }}
          body: |
            Install: npm install @the-bds-maneger/bds_maneger_api@latest
            Install: npm install @the-bds-maneger/bds_maneger_api@${{ env.bds_api_version }}
            Bds Maneger API publish Version: ${{ env.bds_api_version }}
            Bds Maneger API depedencies: ${{ env.bds_api_depe }}