name: "Gitlab Sync repository"
on: 
  push:
   tags:
    - v*
    - V*
    - rc*
   branches:
    - main
  pull_request:
   branches-ignore:
    - dependabot/**/*
    - dependabot**

jobs:
  Sync:
    name: Sync gitlab repository
    runs-on: "ubuntu-latest"
    steps:
      - name: Sync 
        uses: Sirherobrine23/SyncMirror@main
        with:
          repo: "The-Bds-Maneger/Bds-Maneger-Core.git"
          host: "https://the-bds-maneger.org"
          user: ${{ secrets.SYNC_USERNAME }}
          passworld: ${{ secrets.SYNC_PASSWORLD }}
          force: true
